blank_issues_enabled: true
contact_links:
  - name: ðŸ“š Documentation
    url: https://fluentassertions.com/introduction/
    about: Read our comprehensive documentation.
  - name: ðŸ’¬ Ask on Stack Overflow
    url: https://stackoverflow.com/questions/tagged/fluent-assertions
    about: The best place for asking general purpose questions.